name: alchemy-mailings
order: 1
navigation:
  name: 'Mailings'
  controller: admin/mailings
  action: index
  image: /images/alchemy-mailings/mailings.png
  sub_navigation:
    - name: Mailings
      controller: admin/mailings
      action: index
    - name: Newsletter
      controller: admin/newsletters
      action: index
    - name: Kontakte
      controller: admin/contacts
      action: index
    - name: Zielgruppen
      controller: admin/contact_groups
      action: index
    - name: Tags
      controller: admin/tags
      action: index
  nested:
    - controller: admin/mailings
      action: edit_content

settings:
  # mail from
  mail_from: testmail@alchemy-app.com
  # sending mails in chunks of
  send_mails_in_chunks_of: 10
  # sending mail chunks every minute
  send_mail_chunks_every: 1
