name: alchemy-mailings

navigation:
  name: 'Mailings'
  controller: admin/mailings
  action: index
  image: /images/alchemy-mailings/mailings.png
  sub_navigation:
    - name: Mailings
      controller: admin/mailings
      action: index
    - name: Newsletter
      controller: admin/newsletters
      action: index
    - name: Kontakte
      controller: admin/contacts
      action: index
    - name: Gruppen
      controller: admin/contact_groups
      action: index
    - name: Tags
      controller: admin/tags
      action: index
  nested:
    - controller: admin/mailings
      action: edit_content

settings:
  mail_from: tvdeyen@gmail.com
  enable_workflow: false

preview_frame:
  controller: admin/mailings
  action: edit
  target_controller: admin/mailings
  target_action: preview
