- name: newsletter_signup_form
  unique: true
  contents:
  - name: newsletter_text
    type: EssenceRichtext
    validate: presence
  - name: followup_page
    type: EssenceRichtext
    validate: presence
  - name: mail_from
    type: EssenceText
    validate: presence
  - name: mail_subject
    type: EssenceText
    validate: presence
  - name: email_text
    type: EssenceRichtext
    validate: presence
  - name: verification_followup_page
    type: EssenceText
    validate: presence

- name: newsletter_signout_form
  unique: true
  contents:
  - name: signout_text
    validate: presence
    type: EssenceRichtext
  - name: followup_page
    type: EssenceText
    validate: presence
  - name: mail_from
    type: EssenceText
    validate: presence
  - name: mail_subject
    type: EssenceText
    validate: presence
  - name: email_text
    type: EssenceRichtext
    validate: presence
  - name: signout_followup_page
    type: EssenceText
    validate: presence
