language: ruby
rvm:
  - 1.9.2
  - 1.9.3
branches:
  only:
    - everyone_is_subscriber
before_script:
  - "sh -c 'cd spec/dummy; RAILS_ENV=test bundle exec rake db:setup'"
script: "bundle exec rspec spec"
