test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: alchemy_crm_test
  pool: 5
  username: root
  password:

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  host: localhost
  database: alchemy_crm_development
  pool: 5
  username: root
  password:
