name: alchemy_crm
engine_name: alchemy_crm
order: 1
navigation:
  name: modules.crm
  controller: alchemy_crm/admin/mailings
  action: index
  image: /assets/alchemy_crm/module_icon.png
  sub_navigation:
    - name: Mailings
      controller: alchemy_crm/admin/mailings
      action: index
    - name: Newsletter
      controller: alchemy_crm/admin/newsletters
      action: index
    - name: Kontakte
      controller: alchemy_crm/admin/contacts
      action: index
      nested_actions: [import]
    - name: Zielgruppen
      controller: alchemy_crm/admin/contact_groups
      action: index
    - name: Tags
      controller: alchemy_crm/admin/tags
      action: index
  nested:
    - controller: alchemy_crm/admin/mailings
      action: edit_content
    - controller: alchemy_crm/admin/contacts
      action: import
