name: alchemy_crm
engine_name: alchemy_crm
order: 1
navigation:
  name: 'Mailings'
  controller: admin/mailings
  action: index
  image: /assets/alchemy_crm/module_icon.png
  sub_navigation:
    - name: Mailings
      controller: admin/mailings
      action: index
    - name: Newsletter
      controller: admin/newsletters
      action: index
    - name: Kontakte
      controller: admin/contacts
      action: index
    - name: Zielgruppen
      controller: admin/contact_groups
      action: index
    - name: Tags
      controller: admin/tags
      action: index
  nested:
    - controller: admin/mailings
      action: edit_content
