- name: newsletter_greeting
  unique: true
  contents:
  - name: male_greeting
    type: EssenceText
  - name: female_greeting
    type: EssenceText
  - name: text
    type: EssenceRichtext

- name: newsletter_article
  contents:
  - name: image
    type: EssencePicture
  - name: headline
    type: EssenceText
  - name: text
    type: EssenceRichtext
  - name: link
    type: EssenceLink

# These elements are added by the Alchemy CRM module.

- name: newsletter_signup_form
  unique: true
  contents: 
  - name: choose_newsletter_text
    type: EssenceRichtext
  - name: signed_up_text
    type: EssenceRichtext
    validate: 
    - presence
  - name: verified_text
    type: EssenceRichtext
    validate: 
    - presence
- name: newsletter_signup_mail
  unique: true
  contents: 
  - name: mail_from
    type: EssenceText
    validate: 
    - presence
  - name: subject
    type: EssenceText
    validate: 
    - presence
    take_me_for_preview: true
  - name: text
    type: EssenceRichtext
    validate: 
    - presence
- name: newsletter_signout_form
  unique: true
  contents: 
  - name: signed_out_text
    type: EssenceRichtext
    validate: 
    - presence
  - name: disabled_text
    type: EssenceRichtext
    validate: 
    - presence
- name: newsletter_signout_mail
  unique: true
  contents: 
  - name: mail_from
    type: EssenceText
    validate: 
    - presence
  - name: subject
    type: EssenceText
    validate: 
    - presence
    take_me_for_preview: true
  - name: text
    type: EssenceRichtext
    validate: 
    - presence
